window.language = {
    EN: {
        RELICS_NAMES: ["Ares Relic", "Yggdrasil Relic", "Hermes Relic", "Vulcan Relic", "No Relic"],
        THREATS: ["", "NORMAL", "ADVANCED", "SUPERIOR", "VETERAN", "ELITE", "MASTER", "LEGEND"],
        ARMORS_NAMES: {
            Normal: ['Tiny [ARMOR]', 'Cursed [ARMOR]', 'Ruined [ARMOR]', 'Damaged [ARMOR]', 'Unusable [ARMOR]', 'Rusty [ARMOR]', 'Weakened [ARMOR]', 'Broken [ARMOR]'],
            Common: ['Cheap [ARMOR]', 'Small [ARMOR]', 'Fragile [ARMOR]', 'Chipped [ARMOR]', 'Weak [ARMOR]', 'Used [ARMOR]', 'Battered [ARMOR]', 'Worn [ARMOR]'],
            Uncommon: ['Expensive [ARMOR]', 'Strange [ARMOR]', 'Quirky [ARMOR]', 'Unusual [ARMOR]', 'Undamaged [ARMOR]', 'Clean [ARMOR]', 'Primitive [ARMOR]', 'Fresh [ARMOR]'],
            Rare: ['Nice [ARMOR]', 'Good [ARMOR]', 'Premium [ARMOR]', 'Resistant [ARMOR]', 'Strong [ARMOR]', 'Durable [ARMOR]', 'Polished [ARMOR]', 'Powerful [ARMOR]'],
            Epic: ['Master [ARMOR]', 'Expert [ARMOR]', 'Guardian [ARMOR]', 'Perfect [ARMOR]', 'Balanced [ARMOR]', 'Indestructible [ARMOR]', 'Advanced [ARMOR]', 'Shiny [ARMOR]'],
            Exotic: ['Infinite [ARMOR]', 'Magic [ARMOR]', 'Sacred [ARMOR]', 'Blessed [ARMOR]', 'Ancient [ARMOR]', '[ARMOR] of Alpha', 'Fantastic [ARMOR]', 'Incredible [ARMOR]'],
            Legendary: ['Unreal [ARMOR]', 'Eternal [ARMOR]', '[ARMOR] of Angels', '[ARMOR] of Legend', 'Holy [ARMOR]', 'Celestial [ARMOR]', 'Fairy [ARMOR]', '[ARMOR] of Destiny', 'Transcendent [ARMOR]']
        },
        WEAPONS_NAMES: {
            Normal: ['Tiny [WEAPON]', 'Cursed [WEAPON]', 'Ruined [WEAPON]', 'Damaged [WEAPON]', 'Unusable [WEAPON]', 'Rusty [WEAPON]', 'Weakened [WEAPON]', 'Broken [WEAPON]'],
            Common: ['Cheap [WEAPON]', 'Small [WEAPON]', 'Fragile [WEAPON]', 'Chipped [WEAPON]', 'Weak [WEAPON]', 'Used [WEAPON]', 'Battered [WEAPON]', 'Worn [WEAPON]'],
            Uncommon: ['Big [WEAPON]', 'Strange [WEAPON]', 'Quirky [WEAPON]', 'Unusual [WEAPON]', 'Undamaged [WEAPON]', 'Clean [WEAPON]', 'Primitive [WEAPON]', 'Fresh [WEAPON]'],
            Rare: ['Nice [WEAPON]', 'Good [WEAPON]', 'Premium [WEAPON]', 'Sharp [WEAPON]', 'Resistant [WEAPON]', 'Durable [WEAPON]', 'Polished [WEAPON]', 'Powerful [WEAPON]'],
            Epic: ['Master [WEAPON]', 'Expert [WEAPON]', 'Guardian [WEAPON]', 'Perfect [WEAPON]', 'Balanced [WEAPON]', 'Indestructible [WEAPON]', 'Advanced [WEAPON]', 'Shiny [WEAPON]'],
            Exotic: ['Infinite [WEAPON]', 'Magic [WEAPON]', 'Sacred [WEAPON]', 'Blessed [WEAPON]', 'Ancient [WEAPON]', '[WEAPON] of Alpha', 'Fantastic [WEAPON]', 'Incredible [WEAPON]'],
            Legendary: ['Unreal [WEAPON]', 'Eternal [WEAPON]', '[WEAPON] of Angels', '[WEAPON] of Legend', 'Holy [WEAPON]', 'Celestial [WEAPON]', 'Fairy [WEAPON]', '[WEAPON] of Destiny', 'Transcendent [WEAPON]']
        },
        ARMORS_TYPE: ["", "Helmet", "Chestplate", "Shield", "Boots"],
        WEAPONS_TYPE: ["Sword", "Dagger", "Axe", "Stick", "Bow", "Crossbow"],
        LOCATIONS: {
            0: "The White Light",
            1: "The Shadow Forest",
            2: "The Lost Path",
            3: "Galarius City",
            4: "The Ancient Ruins",
            5: "The Secluded Valley",
            6: "Empire Road",
            7: "Imperium City",
            8: "Central V",
            9: "The Red Portal",
            10: "The Corrupted World",
            11: "The Corrupted Dungeon",
            12: "The Luminous Portal",
            13: "Elysia City",
            14: "Vampire Manor",
            15: "The Red River",
            16: "The Immortals Valley",
            17: "The Vampire Castle",
        },
        ACTIONS: {
            Main: "Main attack",
            Special: "Special attack",
            Specials: "Specials attacks",
            Cover: "Take cover",
            RunAway: "Run away",
            LaunchMission: "Launch chapter",
            CancelMission: "Cancel chapter",
            Travel: "Travel here",
            RecapStory: "View story",
            Story: "Story",
        },
        TASKS: {
            Exploration: ["Exploration", "of [LOCATION]"],
            Mission: ["Mission", "Defeat [COUNT] enemies in [LOCATION]", "Defeat the [CLASS] of [LOCATION]"],
            Dungeon: ["Dungeon", "Clear [LOCATION] ([COUNT] left.)"],
        },
        MENUS: {
            Inventory: "Inventory",
            Dimension: "Dimension",
            Statistics: "Statistics",
            Leaderboard: "Leaderboard",
            Settings: "Settings",
            Credits: "Credits",
            Missions: "Missions",
            Story: "Story",
            Chapters: "Chapters",
            Exploration: "Exploration",
            Guild: "Guild",
        },
        STATUS: {
            NotStarted: "Not Started",
            Incomplete: "Incomplete",
            InProgress: "In Progress",
            Complete: "Complete",
        },
        QUALITIES: {
            Normal: "Normal",
            Common: "Common",
            Uncommon: "Uncommon",
            Rare: "Rare",
            Epic: "Epic",
            Exotic: "Exotic",
            Legendary: "Legendary",
            Divine: "Divine",
        },
        MISC: {
            Weapon: "Weapon",
            Weapons: "Weapons",
            Armor: "Armor",
            Armors: "Armors",
            PowerGem: "Power Gem",
            PowerGems: "Power Gems",
            LifeGem: "Life Gem",
            LifeGems: "Life Gems",
            Relic: "Relic",
            Relics: "Relics",
            Recovering: "Recovering",
            Missed: "MISSED",
            Level: "Lv.",
            Score: "Score",
            LevelUp: "LEVEL UP",
            Respawning: "Respawning in [COUNT] [SECONDS]",
            Hour: "hour",
            Minute: "minute",
            Second: "second",
            Seconds: "seconds",
            CurrentRatio: "Current Ratio",
            LostExp: "You lost a part of your experience.",
            DungeonFailed: "FORTRESS FAILED",
            DungeonFailedMessage: "You failed to clear the fortress.",
            DefeatedBy: "You were defeated by the [ENEMY] !",
            InventoryFull: "Inventory full, you can't recover any new item.",
            Defeated: "[ENEMY] defeated !",
            YouDefeated: "You have defeated [COUNT] [CLASS] enemies.",
            EXP: "XP",
            SpecialDropped: "[COUNT] Special Attack",
            SpecialsDropped: "[COUNT] Special Attacks",
            MainWeapon: "Main Weapon",
            SpecialWeapon: "Special Weapon",
            NextArmorUnlock: "Next armor piece unlocked at level [LEVEL].",
            Equipment: "Equipment",
            LootItem: "1 [QUALITY] equipment ",
            LootRelic: "1 [QUALITY] relic ",
            LootGem: "1 [QUALITY] gem ",
            Lv: "Lv.",
            ThrowAway: "Throw Away",
            Unequip: "Unequip",
            Cover: "Next cover in [COUNT].",
            Retreat: "Next retreat in [COUNT].",
            MaxLevelForArea: "Maximum level has been reached for this area, please check the next available mission.",
            AvailableMission: "New mission unlocked! Are you ready to continue your adventure?",
            Quests: "Quests",
            Titles: "Titles",
            Bank: "Bank",
            Shop: "Shop"
        },
        FORMAT: {
            ENEMIES: "[CLASS] [NAME]"
        },
        STATS: {
            Identification: "Identification",
            Ranking: "Ranking",
            TimePlayed: "Time Played",
            CurrentLevel: "Current Level",
            Class: "Class",
            TotalDamage: "Total Damage Dealt",
            TotalLife: "Total Maximum Life",
            EquipmentScore: "Equipment Score",
            DimensionalDiffculty: "Dimensional Diffculty",
            DungeonsDefeated: "Dungeons Defeated",
            MainWeaponDamage: "Main Weapon Damage",
            SpecialWeaponDamage: "Special Weapon Damage",
            HelmetBaseLife: "Helmet Base Life",
            ArmorBaseLife: "Armor Base Life",
            ShieldBaseLife: "Shield Base Life",
            BootsBaseLife: "Boots Base Life",
            GameVersion: "Game Version",
            Defeated: "[COUNT] Defeated",
            Kills: "[CLASS] Kills",
            Ratio: "Ratio (K/D)",
            TotalKills: "Total Kills",
            TotalDeaths: "Total Deaths",
        },
        RELICS: [
            "",
            "Power bonus of [BONUS]",
            "Life bonus of [BONUS]",
            "Minimal drop quality [BONUS]",
            "Max Score +[BONUS]",
        ],
        REWARDS: [
            "Currently set to <span class='pw green'>show all rewards</span>.",
            "Currently set to <span class='pw red'>hide all rewards</span>.",
            "Currently set to <span class='pw yellow'>show only rewards with loot</span>."
        ]
    },
    FR: {
        RELICS_NAMES: ["Relique d'Arès", "Relique d'Yggdrasil", "Relique d'Hermès", "Relique de Vulcain", "Pas de Relique"],
        THREATS: ["", "NORMAL", "AVANCÉ", "SUPÉRIEUR", "VÉTÉRAN", "ÉLITE", "MAÎTRE", "LÉGENDE"],
        ARMORS_NAMES: {
            Normal: ['Minuscule [ARMOR]', '[ARMOR] Maudit', '[ARMOR] Ruiné', '[ARMOR] Endommagé', '[ARMOR] Inutilisable', '[ARMOR] Rouillé', '[ARMOR] Merdique', '[ARMOR] Brisé'],
            Common: ['[ARMOR] Rayé', '[ARMOR] Abimé', '[ARMOR] Fragile', '[ARMOR] Ébréché', 'Faible [ARMOR]', '[ARMOR] Utilisé', '[ARMOR] Usé', '[ARMOR] Cabossé'],
            Uncommon: ['[ARMOR] Acceptable', 'Grand [ARMOR]', '[ARMOR] Onéreux', '[ARMOR] Lumineux', '[ARMOR] Intacte', '[ARMOR] Propre', '[ARMOR] Basique', '[ARMOR] Neuf'],
            Rare: ['[ARMOR] Superbe', '[ARMOR] Immuable', '[ARMOR] Premium', '[ARMOR] Résistant', '[ARMOR] Solide', '[ARMOR] Durable', '[ARMOR] Brillant', '[ARMOR] Puissant'],
            Epic: ['[ARMOR] de Maître', '[ARMOR] d\'Expert', '[ARMOR] de Gardien', '[ARMOR] Parfait', '[ARMOR] Reluisant', '[ARMOR] Indestructible', '[ARMOR] Avancé', '[ARMOR] Brillant'],
            Exotic: ['[ARMOR] Infini', '[ARMOR] Magique', '[ARMOR] Sacré', '[ARMOR] Béni', '[ARMOR] Reliquat', '[ARMOR] d\'Alpha', '[ARMOR] Fantastique', '[ARMOR] Incroyable'],
            Legendary: ['[ARMOR] Irréel', '[ARMOR] Éternel', '[ARMOR] des Anges', '[ARMOR] de Légende', '[ARMOR] Saint', '[ARMOR] Céleste', '[ARMOR] Féérique', '[ARMOR] de la Destinée', '[ARMOR] de la Transcendance']
        },
        WEAPONS_NAMES: {
            Normal: ['[WEAPON] Minuscule', '[WEAPON] Maudite', '[WEAPON] Ruinée', '[WEAPON] Endommagée', '[WEAPON] Inutilisable', '[WEAPON] Rouillée', '[WEAPON] Merdique', '[WEAPON] Brisée'],
            Common: ['[WEAPON] Rayée', '[WEAPON] Abimée', '[WEAPON] Fragile', '[WEAPON] Émoussée', 'Faible [WEAPON]', '[WEAPON] d\'Occasion', '[WEAPON] Usée', '[WEAPON] Amochée'],
            Uncommon: ['[WEAPON] Acceptable', 'Grande [WEAPON]', '[WEAPON] Onéreuse', '[WEAPON] Résistante', '[WEAPON] Intacte', '[WEAPON] Propre', '[WEAPON] Basique', '[WEAPON] Neuve'],
            Rare: ['Bonne [WEAPON]', '[WEAPON] Immuable', '[WEAPON] Premium', '[WEAPON] Résistante', '[WEAPON] Tranchante', '[WEAPON] Durable', '[WEAPON] Brillante', '[WEAPON] Puissante'],
            Epic: ['[WEAPON] de Maître', '[WEAPON] d\'Expert', '[WEAPON] de Gardien', '[WEAPON] Parfaite', '[WEAPON] Équilibrée', '[WEAPON] Indestructible', '[WEAPON] Avancée', '[WEAPON] Brillante'],
            Exotic: ['[WEAPON] Infinie', '[WEAPON] Magique', '[WEAPON] Sacrée', '[WEAPON] Bénie', '[WEAPON] Reliquate', '[WEAPON] d\'Alpha', '[WEAPON] Fantastique', '[WEAPON] Incroyable'],
            Legendary: ['[WEAPON] Irréelle', '[WEAPON] Éternelle', '[WEAPON] des Anges', '[WEAPON] de Légende', 'Sainte [WEAPON]', '[WEAPON] Céleste', '[WEAPON] Féérique', '[WEAPON] de la Destinée', '[WEAPON] de la Transcendance']
        },
        ARMORS_TYPE: ["", "Casque", "Plastron", "Bouclier", "Bottes"],
        WEAPONS_TYPE: ["Épée", "Dague", "Hache", "Baton", "Arc", "Arbalète"],
        LOCATIONS: {
            0: "La Lumière Blanche",
            1: "La Forêt des Ombres",
            2: "Le Chemin Perdu",
            3: "La Ville de Galarius",
            4: "La Montagne sans Fin",
            5: "La Grotte Obscure",
            6: "La Route Impériale",
            7: "La Ville d'Imperium",
            8: "Le Central V",
            9: "Le Portail Rouge",
            10: "Le Monde Corrompu",
            11: "La Forteresse Corrompue",
            12: "Le portail Lumineux",
            13: "La Ville d'Elysia",
            14: "Le Manoir des Vampires",
            15: "La Rivière Rouge",
            16: "La Vallée des Immortels",
            17: "Le Château des Vampires",
        },
        ACTIONS: {
            Main: "Attaque principale",
            Special: "Attaque spéciale",
            Specials: "Attaques spéciales",
            Cover: "Se mettre à couvert",
            RunAway: "Fuir",
            LaunchMission: "Lancer le chapitre",
            CancelMission: "Annuler le chapitre",
            Travel: "Voyager ici",
            RecapStory: "Voir l'histoire",
            Story: "Histoire",
        },
        TASKS: {
            Exploration: ["Exploration", "de [LOCATION]"],
            Mission: ["Mission", "Battre [COUNT] ennemis dans [LOCATION]", "Battre le [CLASS] de [LOCATION]"],
            Dungeon: ["Forteresse", "Nettoyer [LOCATION] ([COUNT] ennemis restants.)"],
        },
        MENUS: {
            Inventory: "Inventaire",
            Dimension: "Dimension",
            Statistics: "Statistiques",
            Leaderboard: "Classement",
            Settings: "Paramètres",
            Credits: "Crédits",
            Missions: "Missions",
            Story: "Histoire",
            Chapters: "Chapitres",
            Exploration: "Exploration",
            Guild: "Guilde",
        },
        STATUS: {
            NotStarted: "Non commencée",
            Incomplete: "Non terminée",
            InProgress: "En cours",
            Complete: "Terminée",
        },
        QUALITIES: {
            Normal: "Normal",
            Common: "Commun",
            Uncommon: "Non Commun",
            Rare: "Rare",
            Epic: "Epique",
            Exotic: "Exotique",
            Legendary: "Légendaire",
            Divine: "Divin",
        },
        MISC: {
            Weapon: "Arme",
            Weapons: "Armes",
            Armor: "Armure",
            Armors: "Armures",
            PowerGem: "Gemme de Puissance",
            PowerGems: "Gemmes de Puissance",
            LifeGem: "Gemme de Vie",
            LifeGems: "Gemmes de Vie",
            Relic: "Relique",
            Relics: "Reliques",
            Recovering: "Récupération",
            Missed: "RATÉ",
            Level: "Niveau",
            Score: "Score",
            LevelUp: "NIVEAU SUPÉRIEUR",
            Respawning: "Réapparition dans [COUNT] [SECONDS]",
            Hour: "heure",
            Minute: "minute",
            Second: "seconde",
            Seconds: "secondes",
            CurrentRatio: "Ratio actuel",
            LostExp: "Vous avez perdu une partie de votre expérience.",
            DungeonFailed: "FORTERESSE ÉCHOUÉE",
            DungeonFailedMessage: "Vous n'avez pas réussi à nettoyer la forteresse.",
            DefeatedBy: "Vous avez été vaincu par [ENEMY] !",
            InventoryFull: "Inventaire plein, vous ne pouvez pas récupérer plus d'objets.",
            Defeated: "[ENEMY] vaincu !",
            YouDefeated: "Vous avez vaincu [COUNT] ennemis de classe [CLASS].",
            EXP: "EXP",
            SpecialDropped: "[COUNT] Attaque Spéciale",
            SpecialsDropped: "[COUNT] Attaques Spéciales",
            MainWeapon: "Arme Principale",
            SpecialWeapon: "Arme Spéciale",
            NextArmorUnlock: "Prochaine pièce d'armure débloquée au niveau [LEVEL].",
            Equipment: "Équipement",
            LootItem: "1 équipement [QUALITY]",
            LootRelic: "1 relique [QUALITY]",
            LootGem: "1 gemme [QUALITY]",
            Lv: "Niv.",
            ThrowAway: "Jeter",
            Unequip: "Désequiper",
            Cover: "Prochaine couverture dans [COUNT].",
            Retreat: "Prochaine fuite dans [COUNT].",
            MaxLevelForArea: "Vous avez atteint le niveau maximal pour cette zone, veuillez regarder les missions disponibles.",
            AvailableMission: "Une mission est disponible pour continuer l'histoire.",
            Quests: "Quêtes",
            Titles: "Titres",
            Bank: "Banque",
            Shop: "Boutique"
        },
        FORMAT: {
            ENEMIES: "[NAME] [CLASS]",
        },
        STATS: {
            Identification: "Pseudo",
            Ranking: "Classement",
            TimePlayed: "Temps de Jeu",
            CurrentLevel: "Niveau Actuel",
            Class: "Classe",
            TotalDamage: "Total de Dégats Infligés",
            TotalLife: "Total de Vie Maximale",
            EquipmentScore: "Score d'Équipement",
            DimensionalDiffculty: "Difficulté Dimensionnelle",
            DungeonsDefeated: "Donjons Vaincus",
            MainWeaponDamage: "Dégats de l'Arme Principale",
            SpecialWeaponDamage: "Dégats de l'Arme Spéciale",
            HelmetBaseLife: "Vie de Base du Casque",
            ArmorBaseLife: "Vie de Base de l'Armure",
            ShieldBaseLife: "Vie de Base du Bouclier",
            BootsBaseLife: "Vie de Base des Bottes",
            GameVersion: "Version du Jeu",
            Defeated: "[COUNT] Vaincus",
            Kills: "[CLASS] Tués",
            Ratio: "Ratio (É/M)",
            TotalKills: "Total de Tués",
            TotalDeaths: "Total de Morts",
        },
        RELICS: [
            "",
            "Bonus de puissance de [BONUS]",
            "Bonus de vie de [BONUS]",
            "Qualité minimale des objets [BONUS]",
            "Score maximal +[BONUS]",
        ],
        REWARDS: [
            "Actuellement définis pour <span class='pw green'>afficher toutes les récompenses</span>.",
            "Actuellement définis pour <span class='pw red'>cacher toutes les récompenses</span>.",
            "Actuellement définis pour <span class='pw yellow'>n'afficher que les récompenses avec du butin</span>."
        ]
    }
};
